### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by nguyendangdung** [cmoussalli/DynThings#4]
I cloned the latest code from master, failed to build however. Because DynThings.Data.Reports is missing DynHighCharts.dll

**Comment by cmoussalli** [comment]
Thank you to highlight this issue, you can find the file in the bin folder.
just remove the reference and add it again.

**Comment by nguyendangdung** [comment]
Hi, the recent commit is missing DynThingsCentral.WebAPI.Client.dll. Can you upload it as well?

**Comment by cmoussalli** [comment]
Thank you to highlight this issue, you can find the file in the "Bins" folder.
